---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: "{{ application_namespace }}"
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
