---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: "{{ application_namespace }}"
spec:
  resources:
    requests:
      storage: 10G
  accessModes:
    - ReadWriteMany
