---
- name: "Copy snippets"
  copy:
    src: "{{ lookup('env', 'PWD') }}/snippets/{{ image }}/{{ item }}"
    dest: "{{ role_path }}/templates/"
    mode: preserve
  with_items: "{{ snippets }}"

- name: "Create Dockerfile for foreman-proxy"
  template:
    src: "Dockerfile.j2"
    dest: "{{ build_dir }}/{{ image }}/Dockerfile"
    mode: 0600

- name: "Remove snippets"
  file:
    path: "{{ role_path }}/templates/{{ item }}"
    state: absent
  with_items: "{{ snippets }}"

- name: "Copy container assets for foreman-proxy to build dir"
  copy:
    src: "{{ role_path }}/files/container_assets"
    dest: "{{ build_dir }}/{{ image }}"
    mode: preserve

- name: "Check if snippets exist"
  stat:
    path: "{{ lookup('env', 'PWD') }}/snippets/{{ image }}/container-assets"
  register: snippets_exist

- name: "Copy additional container assets for foreman-proxy to build dir"
  copy:
    src: "{{ lookup('env', 'PWD') }}/snippets/{{ image }}/container-assets"
    dest: "{{ build_dir }}/{{ image }}"
    mode: preserve
  when: snippets_exist.stat.isdir is defined and snippets_exist.stat.isdir
