---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: "{{ application_namespace }}"
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      targetPort: 5432
      name: port-5432-tcp
      port: 5432
