---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: theforeman
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: centos/postgresql-12-centos7
          env:
            - name: POSTGRESQL_DATABASE
              value: foreman
            - name: POSTGRESQL_USER
              value: foreman
            - name: POSTGRESQL_PASSWORD
              value: foreman
          volumeMounts:
            - readOnly: false
              mountPath: /var/lib/pgsql/data
              name: postgres-data
          ports:
            - containerPort: 5432
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
