---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: "{{ application_namespace }}"
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
