---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: theforeman-ingress
  namespace: theforeman
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: foreman
            port:
              number: 8080
