---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
provisioner:
  name: ansible
  env:
    ANSIBLE_CONFIG: "../../ansible.cfg"
    ANSIBLE_ROLES_PATH: "../../roles"
verifier:
  name: ansible
