apiVersion: apps/v1
kind: Deployment
metadata:
  name: theforeman-operator
  namespace: "{{ application_namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: theforeman-operator
  template:
    metadata:
      labels:
        name: theforeman-operator
    spec:
      serviceAccountName: theforeman-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "{{ operator_image }}"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: "{{ operator_image }}"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "theforeman-operator"
      volumes:
        - name: runner
          emptyDir: {}
