---
apiVersion: v1
kind: Service
metadata:
  name: foreman
  namespace: "{{ application_namespace }}"
  labels:
    app: foreman
spec:
  selector:
    app: foreman
  ports:
    - protocol: TCP
      targetPort: 8080
      name: port-8080-tcp
      port: 8080
