- hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
    state: present
  tasks:
    - name: 'Apply CR change'
      k8s:
        definition: "{{ lookup('template', '/'.join([lookup('env', 'PWD'), 'definitions/theforeman-operator/deploy/crds/theforeman_v1alpha1_foreman_cr.yaml'])) | from_yaml }}"
        state: "{{ state }}"
