---
- hosts: localhost
  gather_facts: no
  vars:
    registry: ''
    image: foreman
    version: latest
    version_build: 1
    snippets: []
    rpms_to_install: []
  roles:
    - role: build-foreman-image
